package org.hurtorius.mirror;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.hurtorius.mirror.core.*;
import java.nio.file.*;
import java.io.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

final class CoreTest {
    @TempDir Path dir;
    private static final String A="00000000-0000-0000-0000-000000000001",B="00000000-0000-0000-0000-000000000002",C="00000000-0000-0000-0000-000000000003";
    @Test void websiteRulesDoNotAcceptSuffixSpoofingOrCredentials(){ScreenSpec s=new ScreenSpec();s.allowedSites.add("example.com");assertTrue(s.siteAllowed("https://docs.example.com/a"));assertFalse(s.siteAllowed("https://example.com.evil.test"));assertFalse(s.siteAllowed("https://notexample.com"));assertFalse(s.siteAllowed("file:///secret"));assertFalse(s.siteAllowed("https://user:password@example.com"));s.blockedSites.add("docs.example.com");assertFalse(s.siteAllowed("https://docs.example.com"));}
    @Test void nonFiniteOversizedAndUnknownSettingsAreRejected(){assertThrows(IllegalArgumentException.class,()->ScreenSpec.read("{\"width\":NaN}"));assertThrows(IllegalArgumentException.class,()->ScreenSpec.read("{\"width\":999}"));assertThrows(IllegalArgumentException.class,()->ScreenSpec.read("{\"source\":\"remote_shell\"}"));assertThrows(IllegalArgumentException.class,()->ScreenSpec.read("{\"schema\":2}"));assertThrows(IllegalArgumentException.class,()->ScreenSpec.read(" ".repeat(24001)));}
    @Test void settingsRoundTripAndCopiesAreIndependent(){ScreenSpec s=new ScreenSpec();s.playlist.add(A);s.viewers.add(B);s.show.add(new ScreenSpec.Cue("play",A,3,0));ScreenSpec copy=s.copy();copy.playlist.clear();assertEquals(List.of(A),s.playlist);assertEquals(3,copy.show.getFirst().seconds());}
    @Test void audienceAndDistanceAreEnforced(){ScreenSpec s=new ScreenSpec();s.audience=ScreenSpec.Audience.SELECTED;s.viewers.add(A);s.viewRange=10;assertTrue(s.canView(A,9.9));assertFalse(s.canView(B,1));assertFalse(s.canView(A,11));s.audience=ScreenSpec.Audience.NOBODY;assertFalse(s.canView(A,0));}
    @Test void consentIsBoundToPlayerAudienceScreenAndEpoch(){Consent c=new Consent();var request=c.request(A,B,C,"nearby:24",1000);assertThrows(IllegalArgumentException.class,()->c.accept(request.id(),B,"nearby:24",1100));assertThrows(IllegalArgumentException.class,()->c.accept(request.id(),C,"selected:24",1100));var grant=c.accept(request.id(),C,"nearby:24",1100);assertTrue(c.allows(A,C,"nearby:24",grant.epoch()));assertFalse(c.allows(B,C,"nearby:24",grant.epoch()));assertFalse(c.allows(A,B,"nearby:24",grant.epoch()));assertFalse(c.allows(A,C,"nearby:24","forged"));assertThrows(IllegalArgumentException.class,()->c.accept(request.id(),C,"nearby:24",1100));c.revoke(A);assertFalse(c.allows(A,C,"nearby:24",grant.epoch()));}
    @Test void expiredAndDisconnectedConsentCannotBeUsed(){Consent c=new Consent();var request=c.request(A,B,C,"nearby",1000);assertThrows(IllegalArgumentException.class,()->c.accept(request.id(),C,"nearby",121001));var second=c.request(A,B,C,"nearby",122000);c.disconnect(C);assertThrows(IllegalArgumentException.class,()->c.accept(second.id(),C,"nearby",122001));}
    @Test void timelinePausesAndSeeksDeterministically(){Anchor a=new Anchor();a.seek(12,1000);a.play(true,1000);assertEquals(14.5,a.positionAt(3500));a.play(false,3500);assertEquals(14.5,a.positionAt(10000));a.seek(2,11000);assertEquals(2,a.positionAt(12000));assertThrows(IllegalArgumentException.class,()->a.seek(Double.NaN,0));}
    @Test void storageRejectsTraversalAndPreservesMalformedWorld()throws Exception{assertThrows(IOException.class,()->AtomicFile.child(dir,"../outside"));assertThrows(IOException.class,()->AtomicFile.child(dir,"a/b"));assertThrows(IOException.class,()->AtomicFile.child(dir,".."));Path file=dir.resolve("world.json");Files.writeString(file,"{invalid");assertThrows(IOException.class,()->WorldStore.load(file));assertEquals("{invalid",Files.readString(file));}
    @Test void pinnedMavenNamesAreValidStorageComponents(){assertDoesNotThrow(()->AtomicFile.child(dir,"jcef-api-jcef-17e805a+cef-152.0.6+g708dc14+chromium-152.0.7977.83.jar"));assertThrows(IOException.class,()->AtomicFile.child(dir,"https:bad"));assertThrows(IOException.class,()->AtomicFile.child(dir,"C:\\outside"));}
    @Test void worldRoundTripKeepsMediaButNeverResumesPrivateBrowser()throws Exception{WorldStore s=new WorldStore();Anchor a=new Anchor();a.owner=A;a.spec.source=ScreenSpec.Source.WEB;a.spec.live=true;a.playing=true;s.anchors.put(a.id,a);Path file=dir.resolve("world.json");s.save(file);WorldStore read=WorldStore.load(file);assertFalse(read.anchors.get(a.id).spec.live);assertFalse(read.anchors.get(a.id).playing);assertEquals(s.world,read.world);}
    @Test void uploadIsBudgetedOrderedAndFingerprintAddressed()throws Exception{MediaRepository r=new MediaRepository(dir);byte[] png;var image=new java.awt.image.BufferedImage(32,32,java.awt.image.BufferedImage.TYPE_INT_RGB);try(var out=new ByteArrayOutputStream()){javax.imageio.ImageIO.write(image,"png",out);png=out.toByteArray();}String transfer=r.begin(A,"image.png","Map","image",png.length,100000,0,0);assertThrows(IOException.class,()->r.chunk(transfer,B,0,png,10));WorldStore.Media m=r.chunk(transfer,A,0,png,10);assertEquals(png.length,m.bytes());assertArrayEquals(png,r.read(m.hash(),0,28000));assertEquals(64,m.hash().length());assertThrows(IOException.class,()->r.begin(A,"large.mp4","","video",512L*1024*1024+1,Long.MAX_VALUE,0,0));assertThrows(IOException.class,()->r.begin(A,"noquota.png","","image",png.length,10,0,0));}
    @Test void wrongOrderAndContentAbortImports()throws Exception{MediaRepository r=new MediaRepository(dir);String t=r.begin(A,"bad.png","","image",8,10000,0,0);assertThrows(IOException.class,()->r.chunk(t,A,1,new byte[8],1));assertThrows(IOException.class,()->r.chunk(t,A,0,new byte[8],1));String next=r.begin(A,"bad.png","","image",8,10000,0,0);assertThrows(IOException.class,()->r.chunk(next,A,0,new byte[8],1));try(var files=Files.list(dir)){assertEquals(0,files.count());}}
    @Test void frameAssemblyBoundsDropsOldAndDuplicateChunks(){FrameAssembler f=new FrameAssembler();assertNull(f.add(1,0,2,new byte[]{1,2},0));assertNull(f.add(1,0,2,new byte[]{1,2},1));assertArrayEquals(new byte[]{1,2,3},f.add(1,1,2,new byte[]{3},2));assertNull(f.add(1,1,2,new byte[]{3},3));assertNull(f.add(0,0,1,new byte[]{4},4));assertNull(f.add(2,0,10,new byte[]{4},4));assertNull(f.add(2,0,1,new byte[28001],4));assertNull(f.add(3,0,2,new byte[]{1},5));assertNull(f.add(3,1,2,new byte[]{2},3000));}
    @Test void timedSubtitlesArePlainAndBounded(){var cues=Subtitles.parse("1\n00:00:01,000 --> 00:00:03,000\n<b>Hello</b>\n\n2\n00:00:04,000 --> 00:00:05,000\nGoodbye\n");assertEquals("",Subtitles.at(cues,0));assertEquals("Hello",Subtitles.at(cues,1));assertEquals("",Subtitles.at(cues,3));assertEquals("Goodbye",Subtitles.at(cues,4.5));assertThrows(IllegalArgumentException.class,()->Subtitles.parse("00:99:00,000 --> 01:00:00,000\nbad"));assertThrows(IllegalArgumentException.class,()->Subtitles.parse("x".repeat(262145)));}
    @Test void customOutlinesCannotSelfIntersectOrCollapse(){var points=List.of(new Outline.Point(0,0),new Outline.Point(1,1),new Outline.Point(0,1),new Outline.Point(1,0));assertThrows(IllegalArgumentException.class,()->Outline.validate(points));assertDoesNotThrow(()->Outline.validate(Outline.hull(points)));assertThrows(IllegalArgumentException.class,()->Outline.validate(List.of(new Outline.Point(0,0),new Outline.Point(.5,0),new Outline.Point(1,0))));}
}
